class FreeWillAIException(Exception): ...

class NotSupportedError(FreeWillAIException): ...

class UserRequirement(FreeWillAIException): ...

class ContractError(FreeWillAIException): ...

class UnexpectedError(FreeWillAIException): ...

class Fatal(FreeWillAIException): ...
